FROM ubuntu:latest AS base_system
LABEL authors="t"

RUN set -xe \
    && apt-get update -y \
    && apt-get install python3-pip libnfnetlink0 python3 python3-dev libnetfilter-queue1 libnetfilter-queue-dev dsniff net-tools iptables iputils-ping gcc -y

RUN apt-get install -y python3.12-venv
RUN python3 -m venv my-venv
COPY requirements.txt /app/requirements.txt
RUN my-venv/bin/pip install -r /app/requirements.txt

COPY . /app
CMD ["echo", "Done!"]